// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cbixmakinnzxgthonyfs.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNiaXhtYWtpbm56eGd0aG9ueWZzIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIxNjkxOTgsImV4cCI6MjA2Nzc0NTE5OH0.cjO42kbb3rQHmrhLMWT2CeHuEykt7OAVtYR43XBv-Nw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});